import{a as x,S as P,i as f}from"./assets/vendor-BDaiwwc1.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const i of a.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function n(e){if(e.ep)return;e.ep=!0;const a=s(e);fetch(e.href,a)}})();const C="https://pixabay.com/api/";async function y(t,r,s){return await x.get(C,{params:{key:"48819918-ba79d398f7b55c76d8c436738",q:t,page:r,per_page:s,image_type:"photo",orientation:"horizontal",safesearch:!0}})}const d=document.querySelector(".gallery"),L=document.querySelector(".loader-box");function w(t){const{webformatURL:r,largeImageURL:s,tags:n,likes:e,views:a,comments:i,downloads:S}=t;return`
    <div class="photo-card">
      <a href="${s}" target="_blank">
        <img src="${r}" alt="${n}" loading="lazy" />
      </a>
      <div class="info">
        <p><strong>Likes:</strong> ${e}</p>
        <p><strong>Views:</strong> ${a}</p>
        <p><strong>Comments:</strong> ${i}</p>
        <p><strong>Downloads:</strong> ${S}</p>
      </div>
    </div>
  `}const $=new P(".gallery a",{captionsData:"alt",captionDelay:250});function D(t){d.innerHTML=t.map(w).join(""),$.refresh(),b()}function E(){d.classList.add("hidden"),L.classList.remove("hidden")}function b(){d.classList.remove("hidden"),L.classList.add("hidden")}function m(){f.show({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!",messageSize:"16px",messageLineHeight:"24px",messageColor:"white",maxWidth:"432px",backgroundColor:"#EF4040"})}const M=document.querySelector("form"),p=document.querySelector("#query"),l=document.querySelector(".load"),u=document.querySelector(".gallery"),v=document.querySelector(".loader-box-down");M.addEventListener("submit",B);const o={query:"",page:1,total:0,perPage:40};async function B(t){if(t.preventDefault(),o.query=p.value.trim(),!o.query)return m();o.page=1,p.value="",E();try{const r=await y(o.query,o.page,o.perPage),s=r.data.hits;if(o.total=r.data.totalHits,!s||s.length===0)throw g(),h(),new Error("No images found");h(),D(s),q()}catch(r){console.error("❌ Помилка:",r),b(),c(),m()}}function h(){u.innerHTML=""}l.addEventListener("click",async()=>{o.page+=1,g(),I();try{const s=(await y(o.query,o.page,o.perPage)).data.hits.map(w).join("");u.insertAdjacentHTML("beforeend",s),c(),q(),R()}catch(t){console.error("❌ Помилка:",t),c()}});function q(){const t=Math.ceil(o.total/o.perPage);o.page>=t?(g(),O()):H()}function H(){l.classList.remove("hidden")}function g(){l.classList.add("hidden")}function I(){v.classList.remove("hidden")}function c(){v.classList.add("hidden")}function O(){f.show({position:"topRight",message:"We are sorry, but you have reached the end of search results.",messageSize:"16px",messageLineHeight:"24px",messageColor:"black",maxWidth:"432px",backgroundColor:"#007bff"})}function R(){const{height:t}=u.lastElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
