import{a as q,S as v,i as S}from"./assets/vendor-tnUJPedx.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const x="https://pixabay.com/api/";async function p(r,e){return await q.get(x,{params:{key:"48819918-ba79d398f7b55c76d8c436738",q:r,page:e,per_page:40,image_type:"photo",orientation:"horizontal",safesearch:!0}})}const c=document.querySelector(".gallery"),f=document.querySelector(".loader-box");function h(r){const{webformatURL:e,largeImageURL:n,tags:i,likes:t,views:o,comments:s,downloads:b}=r;return`
    <div class="photo-card">
      <a href="${n}" target="_blank">
        <img src="${e}" alt="${i}" loading="lazy" />
      </a>
      <div class="info">
        <p><strong>Likes:</strong> ${t}</p>
        <p><strong>Views:</strong> ${o}</p>
        <p><strong>Comments:</strong> ${s}</p>
        <p><strong>Downloads:</strong> ${b}</p>
      </div>
    </div>
  `}const P=new v(".gallery a",{captionsData:"alt",captionDelay:250});function $(r){c.innerHTML=r.map(h).join(""),P.refresh(),y()}function E(){c.classList.add("hidden"),f.classList.remove("hidden")}function y(){c.classList.remove("hidden"),f.classList.add("hidden")}function u(){S.show({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!",messageSize:"16px",messageLineHeight:"24px",messageColor:"white",maxWidth:"432px",backgroundColor:"#EF4040"})}const I=document.querySelector("form"),g=document.querySelector("#query"),l=document.querySelector(".load"),L=document.querySelector(".gallery");document.querySelector(".loader-box-down");I.addEventListener("submit",M);const a={query:"",page:1,total:0};async function M(r){if(r.preventDefault(),a.query=g.value.trim(),!a.query)return u();a.page=1,g.value="",E();try{const e=await p(a.query,a.page);console.log(e);const n=e.data.hits;if(a.total=e.totalHits,!n||n.length===0)throw d(),m(),new Error("No images found");m(),$(n),w()}catch(e){console.error("❌ Помилка:",e),y(),u()}}function m(){L.innerHTML=""}l.addEventListener("click",async()=>{a.page+=1;try{const e=(await p(a.query,a.page)).data.hits;if(!e||e.length===0){d();return}const n=e.map(h).join("");L.insertAdjacentHTML("beforeend",n),w()}catch(r){console.error("❌ Помилка:",r)}});function O(){l.classList.remove("hidden")}function d(){l.classList.add("hidden")}function w(){const e=Math.ceil(a.total/40);a.page>=e?d():O()}
//# sourceMappingURL=index.js.map
